// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfN9MGP9K3MmQ3pYAOKk0dDXZAHZDNbh8',
    appId: '1:504299671740:android:e7b08eb03ba1a7ffa480b9',
    messagingSenderId: '504299671740',
    projectId: 'flaq-app',
    storageBucket: 'flaq-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1QYfGGO_L7OPRVj_iXV36-qFGPEyObZ4',
    appId: '1:504299671740:ios:7442cce71dcd4fe3a480b9',
    messagingSenderId: '504299671740',
    projectId: 'flaq-app',
    storageBucket: 'flaq-app.appspot.com',
    iosClientId: '504299671740-1i45uh3i4qlm6nihcjnictk8r73ik0uk.apps.googleusercontent.com',
    iosBundleId: 'club.flaq',
  );
}
